
version: "3"
services:
  finlife-spring:
    image: finlife
    ports:
      - "8081:8081"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/finlife?useUnicode=true&characterEncoding=UTF-8
      - spring.datasource.username=root
      - spring.datasource.password=finlife
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
    networks:
      - finlife-docker-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    networks:
      - finlife-docker-net
    environment:
      - MYSQL_ROOT_PASSWORD=finlife
      - MYSQL_DATABASE=finlife
      - MYSQL_USER=finlife
      - MYSQL_PASSWORD=finlife

  finlife-react:
    image: finlife-react
    networks:
      - finlife-docker-net
    ports:
      - "3000:3000"

networks:
  finlife-docker-net:
